image:
  name: gcr.io/kaniko-project/executor:v1.23.2-debug
  entrypoint: [""]

stages:
  - build
  - release

before_script:
  - mkdir -p /kaniko/.docker
  - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json

build:
  stage: build
  script:
    - |
      /kaniko/executor \
        --cache=true \
        --cache-repo $CI_REGISTRY_IMAGE \
        --no-push \
        --context $CI_PROJECT_DIR \
        --dockerfile $CI_PROJECT_DIR/Dockerfile \
        --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
  rules: 
    - if: $CI_COMMIT_BRANCH

release:
  stage: release
  script:
    - |
      /kaniko/executor \
        --cache=true \
        --cache-repo $CI_REGISTRY_IMAGE \
        --context $CI_PROJECT_DIR \
        --dockerfile $CI_PROJECT_DIR/Dockerfile \
        --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
  rules: 
    - if: $CI_COMMIT_TAG
