default:
  image: alpine:latest

stages:
  - build
  - deploy

build-code-job:
  stage: build
  tags:
    - docker
  script:
    - echo "chequea los archivos en este directorio:"
    - ls -lah

build-code-job2:
  stage: build
  tags:
    - docker
  script:
    - echo "este es el segundo trabajo"
    - touch archivo.txt
    - date >> archivo.txt
    - ls
    - cat archivo.txt
