default:
  tags:
    - docker

stages:
  - run

image:
  name: registry.hub.docker.com/drunomics/ubuntu-ansible

variables:
    ANSIBLE_HOST_KEY_CHECKING: 'false'
    ANSIBLE_FORCE_COLOR: 'true'
    ANSIBLE_PYTHON_INTERPRETER: /usr/bin/python3

before_script:
  - apt install -y python3

run:
  stage: run
  script:
    - ansible-playbook main.yml
