# /etc/gitlab-runner/config.toml
concurrent = 1
check_interval = 0
shutdown_timeout = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "runner-d78aeaba73"
  url = "http://gitlab.home.local"
  id = 3
  token = "TOKEN"
  token_obtained_at = 2023-08-08T14:16:07Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "docker"
  listen_address="http://gitlab.home.local" ## opcional
  [runners.cache]
    MaxUploadedArchiveSize = 0
  [runners.docker]
    tls_verify = false
    image = "alpine:latest"
    privileged = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/cache"]
    pull_policy = ["always"]
    shm_size = 0
    extra_hosts = ["gitlab.home.local:192.168.121.77"] ## opcional